L02P02_2022JH650_2022RS650/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using L02P02_2022JH650_2022RS650.Models;
using System.Collections.Immutable;

namespace L02P02_2022JH650_2022RS650.Controllers
{
    public class VentaController : Controller
    {
        private readonly libreriaDbContext _libreriaDBcontext;
        public VentaController(libreriaDbContext libreriaDBcontext)
        {
            _libreriaDBcontext = libreriaDBcontext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CrearCliente(clientes cliente)
        {
            var ultimoId = _libreriaDBcontext.clientes.Max(c => (int?)c.id) ?? 0;
            cliente.id = ultimoId + 1;
            cliente.created_at = DateTime.Now;
            _libreriaDBcontext.Add(cliente);
            _libreriaDBcontext.SaveChanges();

            // Crear el encabezado del pedido
            pedido_encabezado encabezado = new pedido_encabezado();
            encabezado.id_cliente = cliente.id;
            var ultimoIdencabezado = _libreriaDBcontext.pedido_encabezado.Max(p => (int?)p.id) ?? 0;
            encabezado.id = ultimoIdencabezado + 1;
            encabezado.cantidad_libros = 0;
            encabezado.total = 0;
            encabezado.estado = "P";
            _libreriaDBcontext.Add(encabezado);
            _libreriaDBcontext.SaveChanges();

            return RedirectToAction("ListadoLibros");
        }

        public IActionResult ListadoLibros()
        {
            var libros = _libreriaDBcontext.libros.ToList();
            ViewBag.Libros = libros;

            var pedidoEncabezado = _libreriaDBcontext.pedido_encabezado
                .Where(p => p.estado == "P") 
                .OrderByDescending(p => p.id) // Obtener el último pedido abierto con estado "P"
                .FirstOrDefault();

            if (pedidoEncabezado != null)
            {
                var carrito = (from pd in _libreriaDBcontext.pedido_detalle
                               join libro in _libreriaDBcontext.libros on pd.id_libro equals libro.id
                               where pd.id_pedido == pedidoEncabezado.id
                               select new
                               {
                                   libro_nombre = libro.nombre,
                                   precio = libro.precio
                               }).ToList();

                ViewBag.Carrito = carrito;
                ViewBag.Total = pedidoEncabezado.total;
                ViewBag.id2 = pedidoEncabezado.id;



            }

            return View();
        }


        [HttpPost]
        public IActionResult AgregarAlCarrito(int libroId)
        {
            var pedidoEncabezado = _libreriaDBcontext.pedido_encabezado
                .Where(p => p.estado == "P")
                .OrderByDescending(p => p.id) // Último pedido creado (El que acabamos de crear, que tiene estado "P")
                .FirstOrDefault();

            if (pedidoEncabezado == null)
            {
                return RedirectToAction("Index");
            }
            
            // Obtener el libro
            var libro = _libreriaDBcontext.libros.FirstOrDefault(l => l.id == libroId);
            if (libro == null || libro.estado == 'O') // Comprobación sobre la existencia de libro y estado (Que no esté ocupado)
            {
                return RedirectToAction("ListadoLibros");
            }

            // Cambiar el estado del libro a "O" (ocupado)
            libro.estado = 'O';
            _libreriaDBcontext.libros.Update(libro);

            // Crear el detalle del pedido
            var pedidoDetalle = new pedido_detalle
            {
                id = _libreriaDBcontext.pedido_detalle.Max(pd => (int?)pd.id) + 1 ?? 1,
                id_pedido = pedidoEncabezado.id,
                id_libro = libro.id,
                created_at = DateTime.Now
            };

            // Actualizar cantidad y total en el encabezado del pedido
            pedidoEncabezado.cantidad_libros += 1;
            pedidoEncabezado.total += libro.precio;

            _libreriaDBcontext.pedido_detalle.Add(pedidoDetalle);
            _libreriaDBcontext.pedido_encabezado.Update(pedidoEncabezado);
            _libreriaDBcontext.SaveChanges();

            return RedirectToAction("ListadoLibros");
        }
        // prototipo 03
        public IActionResult cerrar(int id)
        {

            //Se pasa un id de pedido_encabezado para encontrar el cliente
            var pedidoEncabezado = (from p in _libreriaDBcontext.pedido_encabezado
                                    join c in _libreriaDBcontext.clientes on p.id_cliente equals c.id
                                    where p.id == id
                                    select c).FirstOrDefault();
            ViewData["pedidoEncabezado"] = pedidoEncabezado;

            var pedidoDetalle = (from p in _libreriaDBcontext.pedido_detalle
                                 join l in _libreriaDBcontext.libros on p.id_libro equals l.id
                                 join a in _libreriaDBcontext.autores on l.id_autor equals a.id
                                 where p.id_pedido == id
                                 select new
                                 {
                                     Idpedido = p.id_pedido,
                                     Id = p.id,
                                     titulo = l.nombre,
                                     precio = l.precio,
                                     autor = a.autor
                                 }).ToList();
            ViewData["pedidoDetalle"] = pedidoDetalle;


            var total = (from p in _libreriaDBcontext.pedido_detalle
                         join pe in _libreriaDBcontext.pedido_encabezado on p.id_pedido equals pe.id
                         where p.id_pedido == id
                         select pe.total).FirstOrDefault();
            ViewBag.total = total;


            var ultimoId = _libreriaDBcontext.pedido_encabezado.Max(c => (int?)c.id) ?? 0;
            return View();
        }
        public IActionResult actualizarencabeezado(int id)
        {
            var pedidoEncabezado = _libreriaDBcontext.pedido_encabezado.FirstOrDefault(p => p.id == id);
            if (pedidoEncabezado == null)
            {
                return NotFound();
            }
            pedidoEncabezado.estado = "C";
            _libreriaDBcontext.pedido_encabezado.Update(pedidoEncabezado);
            _libreriaDBcontext.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

L02P02_2022JH650_2022RS650/Views/Venta/Index.cshtml
@{
    <h1>Venta de Libros</h1>
    <br />
    <form asp-action="CrearCliente">
        <div class="form-group row mb-4">
            <h2>Proceso de venta</h2>
        </div>

        <div class="form-group row mb-4">
            <h3>Datos del Cliente</h3>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblNombre", "Nombre")
            </div>
            <div class="col-sm-4">
                @Html.TextBox("nombre", "", new { @class = "form-control" })
            </div>
            <div class="col-sm-2">
                @Html.Label("lblApellido", "Apellido")
            </div>
            <div class="col-sm-4">
                @Html.TextBox("apellido", "", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblEmail", "Email")
            </div>
            <div class="col-sm-10">
                @Html.TextBox("email", "", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblDireccion", "Dirección")
            </div>
            <div class="col-sm-10">
                @Html.TextArea("direccion", "", new { @class = "form-control", @rows = "2" })
            </div>
        </div>

       

        <div class="form-group row mb-4">
            <div class="col-sm-12">
                <input type="submit" class="btn btn-success" value="Iniciar Venta" style="width: 100%" />
            </div>
        </div>
            
    </form>
}

L02P02_2022JH650_2022RS650/Views/Venta/ListadoLibros.cshtml
@{
    <h1>Venta de Libros</h1>
    <br />
    <form asp-action="AgregarAlCarrito">
        <div class="form-group row mb-4">
            <h2>Listado de Libros</h2>
        </div>

        <div class="form-group row mb-4">
            <h3>Libros Disponibles</h3>
        </div>

        <div class="form-group row mb-4">
            <table class="table">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descripción</th>
                        <th>Precio</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var libro in ViewBag.Libros)
                    {
                        <tr>
                            <td>@libro.nombre</td>
                            <td>@libro.descripcion</td>
                            <td>@libro.precio</td>
                            <td>
                                @if (libro.estado != 'O')  // Verificar si el libro no está ocupado
                                {
                                    <form asp-action="AgregarAlCarrito" method="post">
                                        <input type="hidden" name="libroId" value="@libro.id" />
                                        <button type="submit" class="btn btn-primary">Agregar al Carrito</button>
                                    </form>
                                }
                                else
                                {
                                    <span class="text-muted">Agotado</span>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </form>

    <hr />

    <!-- Mostrar el carrito -->
    <h3>Carrito de Compras</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Título</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.Carrito != null)
            {
                foreach (var item in ViewBag.Carrito)
                {
                    <tr>
                        <td>@item.libro_nombre</td>
                        <td>@item.precio</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="2">No hay productos en el carrito.</td>
                </tr>
            }
        </tbody>
    </table>

    <div class="form-group row mb-4">
        <h4>Total: @ViewBag.Total</h4>
    </div>

    <form asp-action="cerrar">
        <div class="form-group row mb-4">
            <div class="col-sm-12">
				<input type="hidden" name="id" value="@ViewBag.id2" />
                <input type="submit" class="btn btn-success" value="Completar" style="width: 100%" />
            </div>
        </div>
    </form>
}

L02P02_2022JH650_2022RS650/Views/Venta/cerrar.cshtml
@{
    var clientes = (L02P02_2022JH650_2022RS650.Models.clientes)ViewData["pedidoEncabezado"];
    var primerPedido = (ViewData["pedidoDetalle"] as IEnumerable<dynamic>)?.FirstOrDefault();
}

    


@{
    <h1>Venta de Libros</h1>
    <br />
    <h1>Datos Cliente</h1>
        @Html.Hidden("id_equipo", clientes.id)
        <div class="form-group row mb-4">
            <h2>Proceso de venta</h2>
        </div>

        <div class="form-group row mb-4">
            <h3>Datos del Cliente</h3>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblNombre", "Nombre")
            </div>
            <div class="col-sm-4">
                @Html.TextBox("nombre", clientes.nombre, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="col-sm-2">
                @Html.Label("lblApellido", "Apellido")
            </div>
            <div class="col-sm-4">
                @Html.TextBox("apellido", clientes.apellido, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblEmail", "Email")
            </div>
            <div class="col-sm-10">
                @Html.TextBox("email", clientes.email, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>

        <div class="form-group row mb-4">
            <div class="col-sm-2">
                @Html.Label("lblDireccion", "Dirección")
            </div>
            <div class="col-sm-10">
                @Html.TextArea("direccion", clientes.direccion, new { @class = "form-control", @rows = "1", @readonly = "readonly" })
            </div>
        </div>

    <form asp-action="cerrarVenta">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3>Carrito</h3>
                    <span class="badge bg-primary rounded-pill" id="cantidad-libros">0</span>
                </div>
                <div class="card-body">                
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Equipo</th>
                                    <th>Precio</th>
                                    <th>Autor</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var pedidoDe in (IEnumerable<dynamic>)ViewData["pedidoDetalle"])
                                {
                                    <tr>
                                        <td>@pedidoDe.titulo</td>
                                        <td>@pedidoDe.precio</td>
                                        <td>@pedidoDe.autor</td>

                                    </tr>
                                }
                            </tbody>
                        </table>

                    <div class="d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong id="total-precio">$ @ViewBag.total</strong>
                    </div>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("Cerrar Venta", "actualizarencabeezado", "Venta",
                                  new { id = primerPedido.Idpedido },
                             new { @class = "btn btn-warning" })


                </div>
            </div>
        </div>
    </form>
}